
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	/// <summary>
	/// Treasure pile decorative addon that displays a collection of treasure items.
	/// Generated by CEO's YAAAG addon generator, refactored for maintainability.
	/// Supports 8 different variations in a single generic system.
	/// </summary>
	public class TreasurePileAddon : BaseAddon
	{
		private TreasurePileAddonConstants.TreasurePileVariation m_Variation;

		/// <summary>
		/// Gets the variation of this treasure pile addon
		/// </summary>
		public TreasurePileAddonConstants.TreasurePileVariation Variation
		{
			get { return m_Variation; }
		}

 
		#region Deed Property
		/// <summary>
		/// Gets the deed associated with this addon for placement and removal.
		/// The deed preserves the variation information for reconstruction.
		/// </summary>
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TreasurePileAddonDeed(m_Variation);
			}
		}
		#endregion

		#region Constructors
		/// <summary>
		/// Initializes the treasure pile addon with all decorative components for the specified variation.
		/// Creates AddonComponent instances positioned to form a treasure pile based on the selected variation.
		/// Components include various treasure items like coins, jewels, and decorations.
		/// </summary>
		/// <param name="variation">The treasure pile variation to create</param>
		[Constructable]
		public TreasurePileAddon(TreasurePileAddonConstants.TreasurePileVariation variation = TreasurePileAddonConstants.TreasurePileVariation.Original)
		{
			m_Variation = variation;

			int startIndex = TreasurePileAddonConstants.GetVariationStartIndex(variation);
			int componentCount = TreasurePileAddonConstants.COMPONENT_COUNTS[(int)variation];

			for (int i = 0; i < componentCount; i++)
			{
				int dataIndex = startIndex + (i * 4);
				int itemId = TreasurePileAddonConstants.COMPONENT_DATA[dataIndex];
				int x = TreasurePileAddonConstants.COMPONENT_DATA[dataIndex + 1];
				int y = TreasurePileAddonConstants.COMPONENT_DATA[dataIndex + 2];
				int z = TreasurePileAddonConstants.COMPONENT_DATA[dataIndex + 3];

				AddComponent(new AddonComponent(itemId), x, y, z);
			}
		}

		/// <summary>
		/// Initializes the treasure pile addon with the default variation.
		/// </summary>
		[Constructable]
		public TreasurePileAddon() : this(TreasurePileAddonConstants.TreasurePileVariation.Original)
		{
		}

		/// <summary>
		/// Deserializes a treasure pile addon from saved data.
		/// </summary>
		/// <param name="serial">The serial number of the addon</param>
		public TreasurePileAddon(Serial serial) : base(serial)
		{
		}
		#endregion

		#region Serialization
		/// <summary>
		/// Serializes the treasure pile addon data for saving.
		/// Includes variation information for proper reconstruction.
		/// </summary>
		/// <param name="writer">The generic writer to serialize to</param>
		public override void Serialize(GenericWriter writer)
		{
			base.Serialize(writer);
			writer.Write(TreasurePileAddonConstants.SERIALIZATION_VERSION);
			writer.Write((int)m_Variation);
		}

		/// <summary>
		/// Deserializes the treasure pile addon data when loading.
		/// Handles version compatibility and variation reconstruction.
		/// </summary>
		/// <param name="reader">The generic reader to deserialize from</param>
		public override void Deserialize(GenericReader reader)
		{
			base.Deserialize(reader);
			int version = reader.ReadInt();

			if (version >= 0)
			{
				m_Variation = (TreasurePileAddonConstants.TreasurePileVariation)reader.ReadInt();
			}
			else
			{
				m_Variation = TreasurePileAddonConstants.TreasurePileVariation.Original;
			}
		}
		#endregion
	}

		#region Nested Classes
		/// <summary>
		/// Deed for the TreasurePileAddon that allows players to place and remove the decorative addon.
		/// Provides the mechanism for addon placement in player homes.
		/// Supports all 8 treasure pile variations in a unified system.
		/// </summary>
		public class TreasurePileAddonDeed : BaseAddonDeed
		{
			private TreasurePileAddonConstants.TreasurePileVariation m_Variation;

			/// <summary>
			/// Gets the variation of treasure pile this deed creates
			/// </summary>
			public TreasurePileAddonConstants.TreasurePileVariation Variation
			{
				get { return m_Variation; }
			}

			#region Deed Property
			/// <summary>
			/// Gets the addon instance that this deed creates when placed.
			/// Creates the addon with the correct variation preserved from the deed.
			/// </summary>
			public override BaseAddon Addon
			{
				get
				{
					return new TreasurePileAddon(m_Variation);
				}
			}
			#endregion

			#region Constructors
			/// <summary>
			/// Creates a new treasure pile addon deed with the default variation.
			/// Initializes the deed with appropriate item properties and localized name.
			/// </summary>
			[Constructable]
			public TreasurePileAddonDeed() : this(TreasurePileAddonConstants.TreasurePileVariation.Original)
			{
			}

			/// <summary>
			/// Creates a new treasure pile addon deed for the specified variation.
			/// Initializes the deed with appropriate item properties and localized name.
			/// </summary>
			/// <param name="variation">The treasure pile variation this deed creates</param>
			[Constructable]
			public TreasurePileAddonDeed(TreasurePileAddonConstants.TreasurePileVariation variation)
			{
				m_Variation = variation;
				ItemID = TreasurePileAddonConstants.DEED_ITEM_ID;
				Weight = TreasurePileAddonConstants.DEED_WEIGHT;
				Hue = 2989;
				Name = string.Format(TreasurePileAddonStringConstants.DEED_NAME_FORMAT, TreasurePileAddonConstants.GetVariationNumber(variation));
			}

			/// <summary>
			/// Deserializes a treasure pile addon deed from saved data.
			/// </summary>
			/// <param name="serial">The serial number of the deed</param>
			public TreasurePileAddonDeed(Serial serial) : base(serial)
			{
			}
			#endregion

			#region Property Display
			/// <summary>
			/// Adds custom properties to the deed's display when examined.
			/// Includes the base addon deed properties plus custom instructions and type label.
			/// </summary>
			/// <param name="list">The property list to add properties to</param>
			public override void AddNameProperties(ObjectPropertyList list)
			{
				base.AddNameProperties(list);
				list.Add(1070722, string.Format("<BASEFONT COLOR=#8be4fc>{0}", TreasurePileAddonConstants.GetVariationTypeLabel(m_Variation)));
				list.Add(1070722, string.Format("<BASEFONT COLOR=#8be4fc>[{0}]", "Para adicionar, clique 2x no baú. Use um machado para remover."));

			}
			#endregion

			#region Serialization
			/// <summary>
			/// Serializes the treasure pile addon deed data for saving.
			/// Includes variation information for proper reconstruction.
			/// </summary>
			/// <param name="writer">The generic writer to serialize to</param>
			public override void Serialize(GenericWriter writer)
			{
				base.Serialize(writer);
				writer.Write(TreasurePileAddonConstants.SERIALIZATION_VERSION);
				writer.Write((int)m_Variation);
			}

			/// <summary>
			/// Deserializes the treasure pile addon deed data when loading.
			/// Handles version compatibility and variation reconstruction.
			/// </summary>
			/// <param name="reader">The generic reader to deserialize from</param>
			public override void Deserialize(GenericReader reader)
			{
				base.Deserialize(reader);
				int version = reader.ReadInt();

				if (version >= 0)
				{
					m_Variation = (TreasurePileAddonConstants.TreasurePileVariation)reader.ReadInt();
				}
				else
				{
					m_Variation = TreasurePileAddonConstants.TreasurePileVariation.Original;
				}
			}
			#endregion
		}
		#endregion
}